
FROM node:18-alpine

# กำหนด working directory
WORKDIR /app

# คัดลอก package.json และ package-lock.json ก่อนเพื่อติดตั้ง dependencies
COPY package*.json ./

# ติดตั้ง dependencies
RUN npm install

# คัดลอกโค้ดทั้งหมดไปยัง container
COPY . .

# เปิดพอร์ตที่ใช้ใน React
EXPOSE 5173

# คำสั่งสำหรับรัน React app
CMD ["npm", "start"]