services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - my-laravel-app_laravel_network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=secret

  db:
    image: mysql:8.0
    container_name: localhost
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user 
      MYSQL_PASSWORD: secret 
    ports:
      - "3307:3306" 
    networks:
      - my-laravel-app_laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - my-laravel-app_laravel_network
      
  frontend:
    container_name: react_frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - app
    networks:
      - my-laravel-app_laravel_network

networks:
  my-laravel-app_laravel_network:
    driver: bridge

